### ISSUE TITLE
No module named 'pyfiglet'

### ISSUE THREAD

**Issue by fpusersuggest** [HalilDeniz/DNSWatch#14]
Hello I have some problem to run DNSWatch.

```$ python3 dnswatch.py                   
/usr/local/lib/python3.10/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release    
  cipher=algorithms.Blowfish,           
/usr/local/lib/python3.10/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated and will be removed in a future release    
  cipher=algorithms.CAST5,              
Traceback (most recent call last):      
  File "/home/myuser/github/DNSWatch/dnswatch.py", line 8, in <module>    
    from source.dnsfiglet import dnsfiglet    
  File "/home/myuser/github/DNSWatch/source/dnsfiglet.py", line 1, in <module>    
    import pyfiglet                     
ModuleNotFoundError: No module named 'pyfiglet'    
```

I tried to install pyfiglet with `$ pipx install pyfiglet` but seems that the script is not callable as module:
```
$ pipx install pyfiglet
  installed package pyfiglet 1.0.2, installed using Python 3.10.14
  These apps are now globally available
    - pyfiglet
done! ✨ 🌟 ✨
```
and

```
$ python3.10 
Python 3.10.14 (main, Apr 13 2024, 11:52:53) [Clang 16.0.6 ] on openbsd7
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfiglet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyfiglet'
```

but exist as program

```
$ pyfiglet "Hello World!"
 _   _      _ _        __        __         _     _ _ 
| | | | ___| | | ___   \ \      / /__  _ __| | __| | |
| |_| |/ _ \ | |/ _ \   \ \ /\ / / _ \| '__| |/ _` | |
|  _  |  __/ | | (_) |   \ V  V / (_) | |  | | (_| |_|
|_| |_|\___|_|_|\___/     \_/\_/ \___/|_|  |_|\__,_(_)
                                                      
```

**Comment by HalilDeniz** [comment]
can you run this: **pip install -r requirements.txt**

**Comment by fpusersuggest** [comment]
No, because I'm running on openbsd and here pip is blocked because can make conflicts with system packages. I don't know why it's blocked even as normal user that should not make any conflicts. It only works pipx, but with pipx I can't install libraries.

**Comment by fpusersuggest** [comment]
Ok I solved installing it on virtualenv.

**Comment by fpusersuggest** [comment]
Hello, if I run as user it works, if I run as root does not work.
But if I run as user doesn't work because scapy wants root, but if I run as root does not work because root has not figlet installed. Can I bypass figlet ?

**Comment by HalilDeniz** [comment]
Frankly, I have never encountered such an error before, but if you have coding knowledge, you can of course easily remove figlet, and if you want, you can join our discord server
https://discord.gg/productionbrain

**Comment by fpusersuggest** [comment]
it's a bit more complicate because I'm openbsd and seems a bit different. I run dnswatch with doas that is something like sudo on *bsd and can't see pyfiglet installed. So I installed sudo and now it works.
